apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    app:  meunginx
    cliente: weslley
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: webports
          containerPort: 80
          protocol: TCP