apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: ClusterIP #pode usar LoadBalancer, expoe a porta para internet porém gera custo!
  selector:
    app: meunginx
    cliente: weslley
  ports:
    - protocol: TCP
      port: 80
      targetPort: webports